### PR TITLE
add args for length and letter dictionary

### PR DESCRIPTION
**Pull request by imerkle**
./cracker 1MkupVKiCik9iyfnLrJoZLx9RH4rkF3hnA a@b.c 8 Only3TheseL33ters

### CODE REVIEW

**Comment by nachowski** [comment]
Thanks for the PR! Before I merge it I would like to improve how it handles optional command line params.

For example this invocation would fail even though the salt in optional:
`./cracker 1MkupVKiCik9iyfnLrJoZLx9RH4rkF3hnA 8 Only3TheseL33ters`

Changing the order of params won't fix it because of ambiguous optional params:
`./cracker 1MkupVKiCik9iyfnLrJoZLx9RH4rkF3hnA 8 IsThisASaltOrAWhiteList?`

**Comment by rama942** [comment]
need video tutorial please i'm newbee, i'm using OS windows,

**Comment by 199862** [comment]
For your list of Ideas. Log results. Obviously this program is run 24 hrs 3 or more Windows cmd. In case of an electrical failure all the work is gone, if is the case you had found the phrase, you’ll never know.

**Comment by 199862** [comment]
Just information. I selected a phrase=WarpWall , unique letters=Warpl , there are 390,000 combinations.
I run your program and found duplicates in a universe of 82778 combinations.
duplicate

**Comment by nachowski** [comment]
@199862 you are correct, the script has no memory of previous attempts and on a small enough keyspace will indeed attempt the same key many times. The script does not perform an exhaustive search either.

There are some ideas to write a bloom filter to prevent this but I'm not sure how efficient that will be in the long run.

**Pull request closed without merging**
